language: node_js
node_js:
  - "6"
services:
  - postgresql
before_script:
  - psql -c 'create database geo_arg_production;' -U postgres
  - psql -c 'create extension postgis;' -U postgres
  - npm install
  - npm start
script:
  - npm test
notifications:
  email: false
env:
  - NODE_ENV=production
